openapi: 3.0.3
info:
  title: maven-2
  description: |-
    maven 2
  version: 0.0.1
servers:
  - url: "http://localhost:8080"
  - url: "https://microcks-microcks.apps.cluster-example.com/rest/maven-2/0.0.1"
paths: {}
